version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "github-actions"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      spring-boot:
        patterns:
         - "org.springframework.boot*"
      third-parties:
        exclude-patterns:
          - "org.springframework.boot*"
