services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '25432:5432'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "28080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: com@com.com
      PGADMIN_DEFAULT_PASSWORD: secret