# fly.toml app configuration file generated for billetterie on 2025-04-14T20:04:27-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'billetterie'
primary_region = 'yul'

[env]
  JAVA_OPTS = "-Xmx250M -XX:MaxMetaspaceSize=50M -XX:ReservedCodeCacheSize=50M"
  BPL_JVM_THREAD_COUNT = 25

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512MB'
  cpu_kind = 'shared'
  cpus = 1

[build]
builder = "paketobuildpacks/builder-noble-java-tiny"
#buildpacks = ["gcr.io/paketo-buildpacks/java"]


[build.args]
#BP_NATIVE_IMAGE="true"
#BP_JVM_CDS_ENABLED="true"
#BP_SPRING_AOT_ENABLED="true"
BP_JVM_VERSION="21"
#JAVA_TOOL_OPTIONS='-XX:ActiveProcessorCount=-1'
#CDS_TRAINING_JAVA_TOOL_OPTIONS="-Dspring.jpa.hibernate.ddl-auto=none -Dhibernate.dialect=org.hibernate.dialect.PostgreSQLDialect"
#BP_GRADLE_BUILD_ARGUMENTS="--no-daemon -Dorg.gradle.welcome=never -x collectReachabilityMetadata assemble"
