name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Package and test with Maven
        run: ./mvnw clean package
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            **/target/surefire-reports
#      - uses: superfly/flyctl-actions/setup-flyctl@master
#      - name: Deploy image
#        run: cp fly.toml build/native/nativeCompile/ && cd build/native/nativeCompile/ && flyctl deploy
#        env:
#          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}